// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using INOXCanvasPrototype;
//
//    var layoutsConfigJsonConverter = LayoutsConfigJsonConverter.FromJson(jsonString);

namespace INOXCanvasPrototype
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    using INOXCanvasPrototype;


    public partial class LayoutsConfigJsonConverter
    {
        public static List<LayoutsSets> FromJson(string json) => JsonConvert.DeserializeObject<List<LayoutsSets>>(json, INOXCanvasPrototype.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<LayoutsSets> self) => JsonConvert.SerializeObject(self, INOXCanvasPrototype.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
