// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using INOXCanvasPrototype;
//
//    var layoutsConfigJsonConverter = LayoutsConfigJsonConverter.FromJson(jsonString);

namespace INOXCanvasPrototype.Converters
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    using INOXCanvasPrototype;
    using INOXCanvasPrototype.Models;
    using INOXCanvasPrototype.Converters;


    public partial class LayoutsConfigJsonConverter
    {
        public static List<PlacementGrid_LayoutsSets> FromJson(string json) => JsonConvert.DeserializeObject<List<PlacementGrid_LayoutsSets>>(json, INOXCanvasPrototype.Converters.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<PlacementGrid_LayoutsSets> self) => JsonConvert.SerializeObject(self, INOXCanvasPrototype.Converters.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
